Dnsmasq rolle einrichten
quotengrote/dp_ausb_md pull request #83
Opened 2021-04-13 06:50 UTC by DanielMueller1309

dnsmasq macht nun DNS und DHCP.
Die DNS Einträge stehen in der Hosts Datei und werden via ansible aus dem Templates Ordner übertragen.

Es stellt sich nur noch die frage ob wir die Hosts Datei noch parametrisieren wollen oder ob ich einen weg finde das der DHCP beim vergeben der leases den Hostnamen jeder VM/Client nimmt und diesen selbstständig in seine Hosts einträgt. 

#### Getestet
- [x] Server bekommen beim erstellen DHCP lease
- [x] Server sind via DNS (nach dem was in der Hosts steht) erreichbar

2021-04-13 07:04 UTC, quotengrote commented
Clients die per DHCP einen Lease bekommen sollte DNSmasq auch selber in seine Namensaufloesung schreiben.
Die Hosts muessten also nur fuer statische Adressen noetig sein.

2021-04-13 07:06 UTC, quotengrote requested changes
Siehe Kommentare

2021-04-13 07:06 UTC, quotengrote commented on ansible/ansible.cfg
> +timeout=30
Wofuer wird der Timeout benoetigt?

2021-04-13 07:06 UTC, quotengrote commented on ansible/inventory.yml
>          hosts:
Gruppe und Hostname gleich = ungut, hier besser verschiedene Bezeichnungen waehlen

2021-04-13 07:06 UTC, quotengrote commented on ansible/roles/dnsmasq_server_einrichten/README.md
> +dhcp_dns_ipaddress: "11.10.31.10" # Adresse des dnsmasq servers
Also die Adresse des Namensservers?

2021-04-13 07:13 UTC, DanielMueller1309 commented on ansible/ansible.cfg
> +timeout=30
deshalb: https://github.com/DanielMueller1309/ansible/wiki/Timeout-(12s)-waiting-for-privilege-escalation-prompt
der timeout fehler schien durch eine langsame Netzwerk Verbindung entstanden zu sein

2021-04-13 07:14 UTC, DanielMueller1309 commented on ansible/roles/dnsmasq_server_einrichten/README.md
> +dhcp_dns_ipaddress: "11.10.31.10" # Adresse des dnsmasq servers
ja

2021-04-13 07:21 UTC, quotengrote commented on ansible/ansible.cfg
> +timeout=30
Probier mal bitte ohne, ist bei mir noch nie aufgetreten.

2021-04-13 08:14 UTC, quotengrote commented
Bei der KeePassDB wird es nach ja merge-reihefolge zu konflikten kommen, also hier am besten noch einaml hinschreiben welcher wert ergänzt wurde, das macht die suche dann einfacher

2021-04-13 11:30 UTC, DanielMueller1309 commented on ansible/ansible.cfg
> +timeout=30
hatte es ohne probiert, ging ja nicht, wie gesagt da kam es zu einem timeout, hab das ganze bestimmt mehr als 10 mal getestet es brach immer an einem anderem punkt des scripts ab

2021-04-13 11:34 UTC, DanielMueller1309 commented on ansible/roles/dnsmasq_server_einrichten/README.md
> +dhcp_dns_ipaddress: "11.10.31.10" # Adresse des dnsmasq servers
ja aber es ist die adresse des dnsmasq servers der auch dhcp macht und wenn dhcp auch ntp dns und gateway verteilt wird diese variable auch als dns-variable genutzt um nicht noch extra eine an zu legen

2021-04-13 11:35 UTC, DanielMueller1309 commented
bei der keepass wurde folgendes ergänzt:
decrypt passwort für --ask-vault-pass

2021-04-13 12:22 UTC, quotengrote commented on ansible/ansible.cfg
> +timeout=30
Welches Script? Für die Rolle Bootstrap + Packages ging es auch ohne.

2021-04-13 12:24 UTC, quotengrote commented on ansible/roles/dnsmasq_server_einrichten/README.md
> +dhcp_dns_ipaddress: "11.10.31.10" # Adresse des dnsmasq servers
Das ist Bad-Practice: nur weil die Variable den gleichen Wert hat, hat sie nicht die gleiche Bedeutung, was passiert denn wenn ich mehrere DNS-Server habe oder z.B. den DNS auf einem anderen Server läuft?

2021-04-13 12:24 UTC, quotengrote commented
> bei der keepass wurde folgendes ergänzt:
> decrypt passwort für --ask-vault-pass

In den commit du Nase :-D

2021-04-13 12:26 UTC, quotengrote commented
Mittelfristig ist es für alle in der Rolle(jeder Rolle!) "notwendig" das ein gemeinsamer Präfix vorhanden ist.

2021-04-15 05:57 UTC, DanielMueller1309 commented
nach ansible Konvention mit GitHub Name oder einer für das Projekt?

2021-04-20 05:36 UTC, quotengrote commented
Behebst du hier bitte den Merge-Konflikt, dann gucke ich nochmal durch und merge.

2021-04-20 06:35 UTC, DanielMueller1309 commented
Es kommen hier sowieso gleich noch mal ein paar commits da sich beim testen rausstellte das ich noch einige Tasks für einige Templates vergessen habe

2021-04-20 08:46 UTC, quotengrote commented
Der Konflikt ist noch da...

2021-04-21 05:42 UTC, quotengrote requested changes
Präfix für Vars

2021-04-21 07:34 UTC, quotengrote commented
Präfix fehlt noch überall

2021-04-21 11:22 UTC, quotengrote commented
Jetzt nur noch die Variablen...

2021-04-27 09:22 UTC, closed without merging